### ISSUE TITLE
migrate test suite from example2 (harness) to unit test infrastructure

### ISSUE THREAD

**Issue by bchurchill** [bchurchill/badi-cal#13]
(should be self-explanatory)

**Comment by brenmcnamara** [comment]
Hey Berkeley, I want to assign this to myself, but Github won't let me. I may need collaborator permissions. Can you either assign this to me or give me collaborate permissions so I may assign this to myself, thanks!

**Comment by bchurchill** [comment]
It looks like only collaborators can be assigned, so I made you one.  My only hesitation is that I would like to be sure to understand everything that goes into the repository.  One nice procedure that we use on some of my other projects is to always use the ticket number in a commit message, and ensure that every commit is associated with some ticket or another.  For example, "Working on Foobar for #12032".  Github will even detect this and do nice things, like link the commit onto the ticket page.  If you write "Fixed foobar.  Closes #10235." it will also close that issue.  

I'll start doing this myself too.  When everyone does it, tracking the changes is much easier.  Everyone can easily see what's changing in the code and why.
