### ISSUE TITLE
Leap year

### ISSUE THREAD

**Issue by wayferer** [bchurchill/badi-cal#3]
Does badi.js take leap years into account? i.e. if looking for when Naw Ruz is next year is badi.js taking into account that next year is a leap year?

**Comment by bchurchill** [comment]
Yes it does.  These details are burried in the external dependencies
that use the algorithms from Meeus.  It's not explicit in the badi.js
file because most of the rest is taken care of by the built-in
javascript dates.  You can always double-check the dates using the demo
application.

**Comment by wayferer** [comment]
Awesome. I just checked and its the same as here http://www.bahaidate.today/table-of-dates/ which I belive is using the Ruby gem. Although I think this site http://calendar.bahaiq.com/173/1 has it wrong then?

**Comment by bchurchill** [comment]
I think calendar.bahaiq.com has not been updated since the UHJ
implemented the Badi calendar, so it's no longer correct.

**Comment by wayferer** [comment]
Oh ok thanks :)
