### ISSUE TITLE
Converting 'Date' to 'BadiDate'

### ISSUE THREAD

**Issue by wayferer** [bchurchill/badi-cal#5]
Hey. So I'm not sure if I have run into an issue or it's just my lack of understanding but I think there is something wrong. When I run the following:

```
var todayDate = new Date();
var todayDateBadi = new BadiCal.gregorian_to_badi(todayDate);
console.log(todayDate, todayDateBadi.toString(), BadiCal.find_naw_ruz(todayDate.getUTCFullYear()))
```

on my machine I get:

```
Thu Jun 25 2015 05:36:33 GMT-0600 (CST) "2 Raḥmat 172" Fri Mar 20 2015 18:00:00 GMT-0600 (CST)
```

but when I run it on a device with its location settings set to NZ timezone I get:

```
Thu Jun 25 2015 23:37:09 GMT+1200 (NZST) "2 Raḥmat 172" Sat Mar 21 2015 13:00:00 GMT+1300 (NZDT)
```

The sunset time for today in NZ was 5:12pm so shouldn't it be returning "3 Rahmat 172"?

**Comment by bchurchill** [comment]
The specification for `gregorian_to_badi` is probably not what you're expecting.  IIRC, It takes the Gregorian UTC date from the `Date` object passed to the function, completely ignores the time, and computes what Badi day for someone in UTC before sunset.  All the computations assume the time is 00:00:00 UTC.  Also, this function has no knowledge of your location or the actual sunrise/sunset times, so it's not capable of doing what you want I think.

So, in both of your examples, it saw that the date was June 25th in UTC, and found the equivalent Badi Date assuming daytime in UTC, which is 2 Rahmat 172.  Does that make sense?

Admittedly, this is all messy and complicated, and javascript isn't helping.  It's entirely possible that some timezone on some browser is broken, but I don't think we've found that yet!  Your report really scared me at first though :)

All this actually suggests to me a redesign is in order.  Right now the `BadiDate` class just represents a (year, month, day).  However, the corresponding JS `Date` class includes dates and times.  So really, a `BadiDate` should hold (year, month, day, hours after sunset, latitude, longitude).  Then, to convert from a `Date` to a `BadiDate` we would need to specify a latitude/longitude along with the `Date`, and then we can do all the sunrise/sunset calculations to get the right `BadiDate` with the right number of hours after sunset.  We could also write functions to convert the `BadiDate` from one location to another location, and a function to convert back to the standard `Date` object.

This is making me realize a fundamental difference between the date&time system we use and the Badi calendar.  In the modern system, the current time is the same for the entire "timezone".  In fact, you could say that if you measure UTC, everyone on earth observes the same time.  But on the Badi calendar, the actual date and time depend on the exact place you're standing.  You can think of every point of the earth as its own timezone.  My guess is that the equivalence of UTC for the Badi calendar is the time in Tehran.

**Comment by wayferer** [comment]
Yes I think that makes a bit more sense now. I haven't made a PR yet but I have this function that seems to be returning the correct sunset/sunrise times based on lat/long info that might be useful:

```
/** Returns sunset in Tehran on a given gregorian day */
  tehran_sunset: function (date) {
    return BadiCal.find_sunset(date,BadiData.tehran_latitude,BadiData.tehran_longitude);
  },

  /** Returns sunset on a given gregorian day */
  find_sunset: function (date,latitude,longitude) {

    // Get UTC hours of Sunset
    var sunset = BlueYonder.SunRiseSet(
                  date.getUTCFullYear(),
                  date.getUTCMonth()+1,
                  date.getUTCDate(),
                  latitude,
                  longitude)[1];

    var sunset_hours = Math.floor(sunset);
    var sunset_minutes = Math.floor((sunset - sunset_hours)*60);
    var sunset_seconds = Math.floor(((sunset - sunset_hours)*60 - sunset_minutes)*60);

    // Put this into a Date object
    var sunset_utc = new Date(Date.UTC(
                  date.getUTCFullYear(),
                  date.getUTCMonth(),
                  date.getUTCDate(),
                  sunset_hours,
                  sunset_minutes,
                  sunset_seconds));

    return sunset_utc;
  },
```

It's just an extension of what was already there. I have tested it with different timezones and it returns the correct time.

Sadly, while I mostly understand what you are describing, I don't enough to be able to implement it. Do you think you will have time or should I try reaching out to someone else who may be able to help?

**Comment by bchurchill** [comment]
That code looks good.  Feel free to submit a PR at your convenience.

As for the redesign I described, I'm happy to do that.  It's pretty involved.  Would you need to use that functionality soon?  If not I would probably postpone working on it.

**Comment by wayferer** [comment]
Fairly soon. I'm hoping to get this little app done in the next month or so before our little baby arrives :)

Also, do you have an Android or iOS device? Would be interested in being part of the 'beta' group?

**Comment by bchurchill** [comment]
Darn, ok.  What's the key functionality you need soon?  Date + Latitude Longitude -> Correct Badi day?  I might be able to do that in the next week or so, but I'm pretty busy these days.

I have an Android and can beta it, keeping in mind I don't have much time to do real testing.

**Comment by wayferer** [comment]
Yup. I don't want to add extra burden on you though so if you're too busy I can try finding another person to help.

No worries, it's just handy to have people in different locations with different devices just fire it up occasionally to make sure it's functional enough :) I do need an email address that you have set on your phone though, is the one on your profile good?

**Comment by bchurchill** [comment]
It seems like a reasonable enough thing for me to do :)  It shouldn't take too long.

**Comment by wayferer** [comment]
Thanks!

**Comment by bchurchill** [comment]
Could you put in a PR for the new function you wrote?

**Comment by wayferer** [comment]
Done https://github.com/bchurchill/badi-cal/pull/7

**Comment by bchurchill** [comment]
Ok, I've pushed the redesign that I described, so now you should have a function that does as you want.  Just do `gregorian_to_badi(date, place)`.  `place` needs to be an object with `latitude` and `longitude` fields.  You can construct one with `loc = new BadiCal.Location(lat, lon)`, for example.

This isn't thoroughly tested; I haven't merged this code into the gh-pages branch which shows up on the website.  Please take a look, and if you like it, feel free to close this ticket.

**Comment by bchurchill** [comment]
And yes, my profile email address is fine.

**Comment by wayferer** [comment]
Thank you! I will give it a test this morning and let you know.

**Comment by wayferer** [comment]
That seems to have done the trick. My location returns:

```
Fri Jun 26 2015 05:32:37 GMT-0600 (CST) "3 Raḥmat 172" Fri Mar 20 2015 18:00:00 GMT-0600 (CST)
```

NZ location returns:

```
Fri Jun 26 2015 23:33:40 GMT+1200 (NZST) "4 Raḥmat 172" Sat Mar 21 2015 13:00:00 GMT+1300 (NZDT)
```

I'm marking this closed for now.

**Comment by bchurchill** [comment]
Cool!  Be careful about the Naw Ruz date.  That object represents the time 12 hours into the day in Tehran.  That way, the utc day/month/year are right, but you don't want to show that object to users in their own timezone.

<div>-------- Original message --------</div><div>From: Abdullah Norozi Iranzad notifications@github.com </div><div>Date:06/26/2015  04:35  (GMT-08:00) </div><div>To: bchurchill/badi-cal badi-cal@noreply.github.com </div><div>Cc: Berkeley Churchill berkeleychurchill@gmail.com </div><div>Subject: Re: [badi-cal] Converting 'Date' to 'BadiDate' (#5) </div><div>
</div>That seems to have done the trick. My location returns:

Fri Jun 26 2015 05:32:37 GMT-0600 (CST) "3 Raḥmat 172" Fri Mar 20 2015 18:00:00 GMT-0600 (CST)
NZ location returns:

Fri Jun 26 2015 23:33:40 GMT+1200 (NZST) "4 Raḥmat 172" Sat Mar 21 2015 13:00:00 GMT+1300 (NZDT)
I'm marking this closed for now.

**Comment by wayferer** [comment]
Noted. Hopefully, once the app is more stable and you have time, you can review my implementation and give me pointers :)

**Comment by bchurchill** [comment]
One other thing -- this function isn't accurate and breaks for latitudes close to the north pole or the south pole.  When this happens, the 'hours' property of the BadiDate object will be NaN.

**Comment by bchurchill** [comment]
and yes, feel free to send me source for your app when you'd like me to look at it.
