### ISSUE TITLE
Find Days

### ISSUE THREAD

**Issue by wayferer** [bchurchill/badi-cal#8]
Maybe I'm using this wrong but the results here don't look right as Bahá is missing. Thoughts?

![image](https://cloud.githubusercontent.com/assets/1575559/13438026/b50d3e0e-dfac-11e5-8bee-aa54b91b281b.png)

**Comment by bchurchill** [comment]
That does look odd.  What did you run in the javascript console to get this?  I can investigate this tonight.

**Comment by wayferer** [comment]
```
function upcomingEventsList() {
  var todayDate = new Date();
  var upcomingEvents = BadiCal.find_days(todayDate, todayDate.addDays(365));
  console.log(upcomingEvents);
}
```

Thanks!

**Comment by bchurchill** [comment]
One of the risks I've been aware of from the early days of this project is that different web browsers have different javascript implementations that do different things, which can be the source of bugs.

I just tested in Firefox and the latest Chrome and this code seems to work.  If you go to the demo site, https://bchurchill.github.io/badi-cal/, do you see the month of Bahá listed?  I do on both browsers.  Can you tell me what exact web browser and platform you were able to reproduce this on?

Also, are you doing something special with sunset times?  When I print this list I get all the start/end times at 00:00:00 localtime, but yours are a few hours offset.

**Comment by wayferer** [comment]
Yeah I wondered about that so I have checked in Firefox, Chrome and Chrome Canary on the Mac and the app on the phone and got the same result; missing Baha. I tested your demo site and I can see Baha and everything else fine so I will compare my implementation to yours and see what is different and let you know.

I don't think I'm doing anything different. I have made a few changes to the badi.js I have but the find_sunset time is identical to yours on Github.

**Comment by wayferer** [comment]
Ok well that didn't take long. I just compared a few other functions and the error was on my part. I had accidentally moved a variable definition in the find_days function into the wrong place when I was making some location changes a while ago and never noticed :sweat: 

One day soon I will push up my changes (including weekday names and sunrise) and when you have some time I'd appreciate your thoughts.

**Comment by bchurchill** [comment]
Great, I more than welcome your contributions.
